"""
Contoso Patient Portal - Azure Architecture Diagram

Generated by diagram-generator agent
Uses Python 'diagrams' library: https://diagrams.mingrammer.com/

Usage:
    python architecture.py

Output:
    contoso_architecture.png
"""

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import AppServices
from diagrams.azure.database import SQLDatabases
from diagrams.azure.network import VirtualNetworks, Subnets, NetworkSecurityGroupsClassic
from diagrams.azure.security import KeyVaults
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.general import Subscriptions
from diagrams.onprem.client import Users

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
}

with Diagram(
    "Contoso Healthcare Patient Portal",
    show=False,
    direction="TB",
    filename="contoso_architecture",
    graph_attr=graph_attr,
):
    # External users
    patients = Users("10K Patients")
    staff = Users("50 Staff")

    with Cluster("Azure Subscription"):

        with Cluster("Resource Group: rg-contoso-patient-portal-prod"):

            with Cluster("Monitoring"):
                log_analytics = LogAnalyticsWorkspaces(
                    "Log Analytics\n(90-day retention)")
                app_insights = ApplicationInsights("Application\nInsights")

            with Cluster("VNet: 10.0.0.0/16"):

                with Cluster("snet-web (10.0.1.0/24)"):
                    nsg_web = NetworkSecurityGroupsClassic(
                        "NSG-Web\nHTTPS Only")
                    app_service = AppServices(
                        "App Service\nP1v3 Linux\n.NET 8 API")

                with Cluster("snet-pe (10.0.3.0/24)"):
                    nsg_pe = NetworkSecurityGroupsClassic("NSG-PE")

                    with Cluster("Private Endpoints"):
                        pe_sql = Subnets("PE: SQL")
                        pe_kv = Subnets("PE: Key Vault")

                with Cluster("snet-data (10.0.2.0/24)"):
                    nsg_data = NetworkSecurityGroupsClassic(
                        "NSG-Data\nFrom Web Only")
                    sql_db = SQLDatabases(
                        "Azure SQL\nS1 (20 DTU)\nPatient Data")
                    key_vault = KeyVaults("Key Vault\nSecrets\nManagement")

    # Connections - Users to App
    patients >> Edge(label="HTTPS", color="darkgreen") >> app_service
    staff >> Edge(label="HTTPS", color="darkgreen") >> app_service

    # Connections - App to Data (via Private Endpoints)
    app_service >> Edge(label="Private Link", color="blue",
                        style="dashed") >> pe_sql
    app_service >> Edge(label="Private Link", color="blue",
                        style="dashed") >> pe_kv

    pe_sql >> Edge(color="blue") >> sql_db
    pe_kv >> Edge(color="blue") >> key_vault

    # Connections - Monitoring
    app_service >> Edge(label="Telemetry", color="orange",
                        style="dotted") >> app_insights
    app_insights >> Edge(color="orange", style="dotted") >> log_analytics
    sql_db >> Edge(label="Audit Logs", color="orange",
                   style="dotted") >> log_analytics
    key_vault >> Edge(label="Access Logs", color="orange",
                      style="dotted") >> log_analytics
